### ISSUE TITLE
Unify replication templates

### ISSUE THREAD

**Issue by mnagy** [sclorg/mysql-container#110]
Replication templates can be unified as was done for PostgreSQL recently. This'll also allow us to make extended tests nicer.

**Comment by bparees** [comment]
@mnagy can you elaborate on what needs to be unified?

**Comment by mnagy** [comment]
@bparees sorry, missed your comment. I wanted to only have one template file and parametrize the image we use.

**Comment by phracek** [comment]
The templates are already unified. See directory examples.
Closing it.
