### ISSUE TITLE
More verbose logging

### ISSUE THREAD

**Issue by mnagy** [sclorg/mysql-container#13]
We would probably like to log queries for example.

**Comment by mfojtik** [comment]
only as special env var, not by default

**Comment by bparees** [comment]
yeah this would be something that should be configurable if it is not already.

**Comment by soltysh** [comment]
@mfojtik +1

**Comment by hhorak** [comment]
logging queries may be quite dangerous, e.g. if anybody stores sensitive data in plain text.. but make it configurable could make sense.

**Comment by hhorak** [comment]
This does not seem to be worth doing it specially, generic way of extending image should be enough. That said, support for extending configuration file passing via ConfigMap will be implemented soon.
