### ISSUE TITLE
MySQL Plugin Installation

### ISSUE THREAD

**Issue by henderb** [sclorg/mysql-container#154]
Is there a supported/existing way to add plugins to this MySQL container? I see a plugin-dir option in my-base.cnf.template for scl compatibility, but nothing seems to call --plugin-load or INSTALL PLUGIN.

https://dev.mysql.com/doc/refman/5.5/en/server-options.html#option_mysqld_plugin-load

I want to build an image that comes up with no extra initialization steps needed in docker-compose or openshift.

**Comment by bparees** [comment]
The assumption is you'd extend this image, so write a dockerfile that does
FROM centos/mysql-56-centos7
RUN <install plugins to plugin dir>

and then run that image.

alternatively you can bindmount a volume containing your plugins, to the plugin dir.
