### ISSUE TITLE
root password is not set correctly

### ISSUE THREAD

**Issue by mhutter** [sclorg/mysql-container#172]
```
sh-4.2$ mysql -uroot
# note that no password is requestsed
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 199
Server version: 5.6.26 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select user,host,Password from mysql.user;
+---------+---------------+-------------------------------------------+
| user    | host          | Password                                  |
+---------+---------------+-------------------------------------------+
| root    | localhost     |                                           |
| root    | mysql-1-1kgat |                                           |
| root    | 127.0.0.1     |                                           |
| root    | ::1           |                                           |
|         | localhost     |                                           |
|         | mysql-1-1kgat |                                           |
| userJJE | %             | *70EC2682A59842A350A3A8B6507ACFA8A9FCD54D |
| root    | %             | *CD600C99BA4328BB6DEC4B0636ED9B751562CDD1 |
+---------+---------------+-------------------------------------------+
8 rows in set (0.00 sec)
```

**Comment by praiskup** [comment]
@mhutter thanks for the report, but where exactly do you see an issue?  it looks like from `localhost` you are allowed to log in without password, but for other containers the password it set fine.

I'm not sure, @bparees is it possible in OpenShift that somebody unexpected (non _admin_ user) would be able to `docker exec` into container?

Maybe this is just documentation issue?

**Comment by mhutter** [comment]
@praiskup jup, I wanted to send a PR to fix the command so the PW gets set for ALL root/host combination. But then I realized this is only a nuisance, since it does not add any security - the only situation where you can log in as `root@localhost` is when you have the root PW in the ENV vars anyway :-)

**Comment by viveksinghggits** [comment]
Hi @mhutter 
If the root password is not being set, is there a way to access the mysql instance from another host.  It seems we can login to the msyql instance without the root password if we are on the same instance but the problem arises when we are trying to login to this instance from another instance.
