### ISSUE TITLE
': not a valid identifierpts/mysql/scl_enable: line 2: unset: `ENV

### ISSUE THREAD

**Issue by coder0wang** [sclorg/mysql-container#177]
I used mysql 5.7 to make images,it was success;but I got a error when I do docker run.
error :
': not a valid identifierpts/mysql/scl_enable: line 2: unset: `ENV
 is probably not installed.-mysql57
/usr/share/container-scripts/mysql/common.sh: line 2: $'\r': command not found
: No such file or directorys/mysql/common.sh: line 3: /usr/share/container-scripts/mysql/helpers.sh
/usr/share/container-scripts/mysql/common.sh: line 4: $'\r': command not found
/usr/share/container-scripts/mysql/common.sh: line 9: $'\r': command not found
/usr/share/container-scripts/mysql/common.sh: line 12: $'\r': command not found
/usr/share/container-scripts/mysql/common.sh: line 13: syntax error near unexpected token `$'{\r''
'usr/share/container-scripts/mysql/common.sh: line 13: `function export_setting_variables() {
/usr/bin/run-mysqld: line 6: export_setting_variables: command not found

My host :
docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

**Comment by bparees** [comment]
I performed a "make TARGET=centos7 VERSION=5.7"

and then ran the resulting image:

```
$ docker run 09e45f77dab7
You must either specify the following environment variables:
  MYSQL_USER (regex: '^[a-zA-Z0-9_]+$')
  MYSQL_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
  MYSQL_DATABASE (regex: '^[a-zA-Z0-9_]+$')
Or the following environment variable:
  MYSQL_ROOT_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
Or both.
Optional Settings:
  MYSQL_LOWER_CASE_TABLE_NAMES (default: 0)
  MYSQL_LOG_QUERIES_ENABLED (default: 0)
  MYSQL_MAX_CONNECTIONS (default: 151)
  MYSQL_FT_MIN_WORD_LEN (default: 4)
  MYSQL_FT_MAX_WORD_LEN (default: 20)
  MYSQL_AIO (default: 1)
  MYSQL_KEY_BUFFER_SIZE (default: 32M or 10% of available memory)
  MYSQL_MAX_ALLOWED_PACKET (default: 200M)
  MYSQL_TABLE_OPEN_CACHE (default: 400)
  MYSQL_SORT_BUFFER_SIZE (default: 256K)
  MYSQL_READ_BUFFER_SIZE (default: 8M or 5% of available memory)
  MYSQL_INNODB_BUFFER_POOL_SIZE (default: 32M or 50% of available memory)
  MYSQL_INNODB_LOG_FILE_SIZE (default: 8M or 15% of available memory)
  MYSQL_INNODB_LOG_BUFFER_SIZE (default: 8M or 15% of available memory)

For more information, see https://github.com/sclorg/mysql-container
```
which is the behavior i'd expect.  Can you provide exact recreate steps?

my docker version is 1.12.6 (go version is not relevant)

git commit is 24ad786981cb2a4b2706cf2fbb5a74c002b39a5a

**Comment by hhorak** [comment]
@coder0wang Do I understand correctly that you build on top of the provided mysql container image?

**Comment by hhorak** [comment]
There is no response for few months, closing it. Feel free to re-open when there is still weird behavior seen.
