### ISSUE TITLE
it went wrong when I scaled rc mysql-slave 

### ISSUE THREAD

**Issue by RobinsChens** [sclorg/mysql-container#182]
2017-05-04T11:49:23.523858Z 0 [Note] InnoDB: Retrying to lock the first data file
2017-05-04T11:49:24.525227Z 0 [ERROR] InnoDB: Unable to lock ./ibdata1 error: 11
2017-05-04T11:49:24.525305Z 0 [Note] InnoDB: Check that you do not already have another mysqld process using the same InnoDB data or log files.
2017-05-04T11:49:25.526448Z 0 [ERROR] InnoDB: Unable to lock ./ibdata1 error: 11

**Comment by bparees** [comment]
Are you using ephemeral volumes for your slaves? If not they are probably sharing a volume and filesystem, hence the lock error.

**Comment by RobinsChens** [comment]
@bparees yes,they are sharing a volume,does it support this way?

**Comment by RobinsChens** [comment]
@bparees How could I solve this problem

**Comment by bparees** [comment]
@RobinsChens use ephemeral volumes for your slaves.  The intent behind the replica example is that your master uses a PV which will keep your data safe, and the slaves, when they start up (or get restarted) will reload their data by syncing from the master.

As you can see that is how our example runs:
master volume:
https://github.com/sclorg/postgresql-container/blob/master/examples/replica/postgresql_replica.json#L185-L193

slave volume:
https://github.com/sclorg/postgresql-container/blob/master/examples/replica/postgresql_replica.json#L302

The other approach is to use DaemonSets where each replica instance gets its own identifier and volume, but we don't have an example of that for mysql.  There is an example of it for mongo:

https://github.com/sclorg/mongodb-container/tree/master/examples/petset

**Comment by RobinsChens** [comment]
@bparees fine,I got it,thank you very much

**Comment by bparees** [comment]
@RobinsChens np
