### ISSUE TITLE
Create run-openshift script

### ISSUE THREAD

**Issue by pvalena** [sclorg/mysql-container#204]
for runing openshift tests and customize for this containers' use-case.

Example:
https://github.com/sclorg/nginx-container/pull/35

And its diff for easier application:
https://patch-diff.githubusercontent.com/raw/sclorg/nginx-container/pull/35.diff

**Comment by phracek** [comment]
This is already implemented by run/test-remote-openshift-cluster. test/run-openshift was deprecated.
