### ISSUE TITLE
Monitoring memory - add custom hook?

### ISSUE THREAD

**Issue by rcwwilliams** [sclorg/mysql-container#205]
We have experienced mysql pods crashing many times over the past few weeks due to OOM errors.

So to avoid this happening unexpectedly we started monitoring memory usage.

There is currently no notification available on OpenShift online for a memory threshold being reached.

So we have devised a custom solution using a script which periodically checks the RSS of the mysql process and enters a row in the database if it breaches a threshold (and we can then send an email to notify our support team).

However, after a pod restart, the script (which runs as a daemon) needs to be started manually.

We tried starting this daemon using the kubernetes hook infrastructure, but it did not work.

Would it be possible to add a custom hook into the mysql image so the daemon could start automatically on restart?

**Comment by omron93** [comment]
Hi,
it is possible to extend this image using `s2i` tool.
(https://github.com/sclorg/mysql-container/tree/master/5.7#extending-image)

As I understand your problem it could be solved using bash script in `/mysql-pre-init/` directory. This script is sourced every time `run-mysqld` is run (https://github.com/sclorg/mysql-container/blob/master/root-common/usr/bin/run-mysqld#L12). So you can run in background everything you want there. One problem you have to solve is correct termination on signal (`run-mysqld` execs `mysqld` so all signals are handled by it. And it does not kill background processes IMHO, so you'll have to create some cleanup function).

@rcwwilliams Please take a look in this. If you have any questions feel free to ask.

**Comment by rcwwilliams** [comment]
Thanks so much - that sounds great.  I will give it a go.

**Comment by rcwwilliams** [comment]
Will a kubernetes PostStart hook have the required permissions to create the mysql-init directory and to copy the script from the persistent volume to that directory?

**Comment by omron93** [comment]
> Will a kubernetes PostStart hook have the required permissions to create the mysql-init directory and to copy the script from the persistent volume to that directory?

I'm not sure. Probably yes, but consider these options:

1. `s2i build` builds new image from application sources (in this case `mysql-pre-init/` scripts are these soures). It creates new image which contains these sources - read more in https://github.com/openshift/source-to-image/ This tool was mainly developed to support extending of images in OpenShift, triggering new builds if app sources changes and so on. So if you are using openshift this is a best way for you.

2. Or you can mount directory which contains `mysql-pre-init` directory directly into `/opt/app-root/src/`. `run-mysqld` sources scripts in `/opt/app-root/src/mysql-pre-init/`. Mount point have to have right permissions - user running inside container (27 by default) has to be able to read them...

**Comment by rcwwilliams** [comment]
Hi Marek

I would like to achieve this without having to build a new image - can this be done using your approach number 2 above?

If so, could we put the scripts on the persistent volume which contains the mysql data (which is of course already mounted at /var/lib/mysql/data)?

If so, please could you give some more instructions for what we would need to do.

Thanks very much.

Kind regards

Robin

**Comment by omron93** [comment]
@rcwwilliams This image is designed to be extendable mainly using s2i (same as other sclorg/ images). And s2i expects source to be present in `/opt/app-root/src/` - so same, extending scripts for this image are expected to be there.
Using mount points is only "workaround" to be able to extend the image without s2i. So it expects same location.

> If so, could we put the scripts on the persistent volume which contains the mysql data (which is of course already mounted at /var/lib/mysql/data)?

As mentioned above, different location is expected. So by default this is not possible.

This could be achieved by `s2i build` which would add simple script running scripts from `/var/lib/mysql/data`.
To note: Openshift triggers new s2i builds automatically for code change or new builder image, so it doesn't require additional work.

**Comment by rcwwilliams** [comment]
Is there a possibility of your enhancing the mysql-container image to allow the optional setting of the location for a pre-init and init script using an environment variable (similar idea to the MYSQL_DEFAULTS_FILE environment variable)?

**Comment by omron93** [comment]
We can discuss it.

It would help if you could describe your reasons - I know that OpenShift online limits number of volumes in free plan, but what is a reason to avoid s2i?

**Comment by rcwwilliams** [comment]
The reason for avoiding s2i is the learning curve and that we prefer to use standard components whenever possible.

We were able to create a custom my.cnf via the MYSQL_DEFAULTS_FILE environment variable and the my.cnf sits on our PV at /var/lib/mysql/data/cnf/my.cnf.

It would be great (and nice, tidy and simple) if we could add an init script in the same way with something like MYSQL_INIT_SCRIPT=/var/lib/mysql/data/sh/init.sh.

**Comment by omron93** [comment]
It came to my mind, that your problem could be solved by redefining `APP_ROOT=/var/lib/mysql/data` on runtime. Then all extending folders (mysql-init/,...) will be searched in PV.

But keep in mind that this isn't supported way and you are doing this on your own risk! And for example in the future some files could be required to be present in `APP_ROOT`.

**Comment by rcwwilliams** [comment]
that sounds like a good idea - please could you advise exactly how I would do that - by setting up the APP_ROOT environment variable in the deployment config?

**Comment by rcwwilliams** [comment]
Thanks Marek - I will try it out once the starter cluster issues are resolved.

**Comment by rcwwilliams** [comment]
Thank you so much Marek - it did the trick perfectly.
