### ISSUE TITLE
Regression introduce with restarting slave pods with PVs

### ISSUE THREAD

**Issue by gabemontero** [sclorg/mysql-container#226]
See https://github.com/sclorg/mysql-container/pull/215/files#r190365336

Should the example/replica template even have a PVC for the slave?
If so, how do we refactor the reference PR/commit to allow slave pod restart per the openshift/origin extended tests I referenced?

thanks

**Comment by hhorak** [comment]
Hm, looking at the change, that was not what I hoped in, I didn't realize how much it is done in case of `run-mysqld` is run even when the datadir is initialized. We should probably do what was done before (revert this part of the change), just run the daemon and not do anything special. Sorry for the issue, I'll take a look at it and prepare a PR.

**Comment by gabemontero** [comment]
@openshift/sig-developer-experience fyi

**Comment by gabemontero** [comment]
@adambkaplan @bparees fyi

**Comment by adambkaplan** [comment]
@hhorak any progress on this item?

**Comment by bparees** [comment]
thanks @hhorak !
