### ISSUE TITLE
You have an x86 dependency hardcoded into the Dockerfile for 8.0

### ISSUE THREAD

**Issue by jonmasters** [sclorg/mysql-container#246]
No architecture dependencies should be hard coded into the Dockerfiles

**Comment by omron93** [comment]
> No architecture dependencies should be hard coded into the Dockerfiles

@jonmasters Somewhere else than in CentOS7 Dockerfile?

About CentOS:
- centos7 is now only for x86_64, so it shouldn't be a problem
- rh-mysql80 isn't properly released here, so workaround with `/x86_64/` is needed. @khardix Please, could you release rh-mysql80? (and probably other RHSCL 3.2 collections)

**Comment by grooverdan** [comment]
note: x86_64 only comes from base image https://github.com/sclorg/s2i-base-container/issues/178

**Comment by phracek** [comment]
@grooverdan As far as I know all architectures are valid, when you have a subscription. rh-mysql80 image is already released.

Closing this issue.

Feel free to re-open it, in case it is still valid.
