### ISSUE TITLE
When mysql8 was initialized and created in Openshift 3.11, it failed due to the existence of the lost+found directory.

### ISSUE THREAD

**Issue by zhengbin78** [sclorg/mysql-container#259]
I found the following script in the file "root-common/usr/libexec/container-setup":
```
#  some config options are only valid for particular versions
if [ "`version2number $MYSQL_VERSION`" -ge "800" ] ; then
    rm -f "${CONTAINER_SCRIPTS_PATH}/cnf/10-mysql57.cnf"
fi

-------
```
cat 10-mysql57.cnf
```
[mysqld]
#  http://www.chriscalender.com/ignoring-the-lostfound-directory-in-your-datadir/
ignore-db-dir=lost+found
```
However: mysql8 on ocp/okd  also needs this parameter, why is it deleted? I think this file 10-mysql57.cnf should be retained, just the file name leads to misunderstanding.

**Comment by phracek** [comment]
Closing this issue. OpenShift 3 is not supported in this repository.

Feel free to use it in OpenSHift 4, where we have a lot of this which covers this issue.

Feel free to re-open it , in case it is still valid.
