### ISSUE TITLE
Is this image production ready with persistent storage? 

### ISSUE THREAD

**Issue by nathanawmk** [sclorg/mysql-container#267]
Is this image production ready with persistent storage?

**Comment by phracek** [comment]
Hi @nathanawmk 

I have solved some problems with the Persistant Storage here https://github.com/sclorg/mysql-container/pull/269. Related Bugzilla report https://bugzilla.redhat.com/show_bug.cgi?id=1653215.

But what do you mean with your question?
Do you have any issues with using persistent storage?
If so, do you have any reproducer or issues?

**Comment by oseiasgomes** [comment]
This versions has error. When I Try create on Deployment with version 8.0, I receive this message:


=> sourcing 25-validate-replication-variables.sh ...
--
  | => sourcing 30-base-config.sh ...
  | ---> 15:19:38     Processing basic MySQL configuration files ...
  | => sourcing 60-replication-config.sh ...
  | => sourcing 70-s2i-config.sh ...
  | ---> 15:19:38     Processing additional arbitrary  MySQL configuration provided by s2i ...
  | => sourcing 40-paas.cnf ...
  | => sourcing 50-my-tuning.cnf ...
  | ---> 15:19:38     Initializing database ...
  | ---> 15:19:38     Running /opt/rh/rh-mysql80/root/usr/libexec/mysqld --initialize --datadir=/var/lib/mysql/data
  | ---> 15:19:38     Starting MySQL server with disabled networking ...
  | ---> 15:19:38     Waiting for MySQL to start ...
  | 2019-10-05T15:19:38.660900Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
  | 2019-10-05T15:19:38.667093Z 0 [System] [MY-010116] [Server] /opt/rh/rh-mysql80/root/usr/libexec/mysqld (mysqld 8.0.13) starting as process 39
  | 2019-10-05T15:19:38.680756Z 1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
  | 2019-10-05T15:19:38.680968Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
  | 2019-10-05T15:19:38.681009Z 0 [ERROR] [MY-010119] [Server] Aborting
  | 2019-10-05T15:19:38.683791Z 0 [System] [MY-010910] [Server] /opt/rh/rh-mysql80/root/usr/libexec/mysqld: Shutdown complete (mysqld 8.0.13)  Source distribution.

**Comment by phracek** [comment]
How do you execute `mysql` S2I image. In Openshift or via `docker/podman`? 
From the log I can see error:
```
 | 2019-10-05T15:19:38.680756Z 1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
```
Do you mount the proper data directory?

https://github.com/sclorg/mysql-container/tree/master/8.0#usage

**Comment by phracek** [comment]
@oseiasgomes Yes, this image is already production ready in OpenShift environment.

We have a lot of tests in OpenShift 4 environment, including persistent storage template.

I guess, this is not valid at all and closing this issue.

Feel free to re-open it and even file a pull request.
