### ISSUE TITLE
How to upgrade from mysql5.7.24 to 5.7.28

### ISSUE THREAD

**Issue by fenggolang** [sclorg/mysql-container#278]
In order to deal with mysql related vulnerabilities, I need to upgrade the default mysql5.7.24 to 5.7.28

How to upgrade from mysql5.7.24 to 5.7.28

I tried to change the Dockerfile and found all kinds of strange errors

**Comment by hhorak** [comment]
Sorry for the late answer. MySQL 5.7 is not supported any more, so no further updates beyond 5.7.24 are available.
https://access.redhat.com/support/policy/updates/rhscl-rhel7
