### ISSUE TITLE
Document selinux relabeling

### ISSUE THREAD

**Issue by mnagy** [sclorg/mysql-container#51]
Document the needed `:Z` option for volumes so SELinux works properly. This needs to be done for all our database images.

**Comment by mnagy** [comment]
Also see https://bugzilla.redhat.com/show_bug.cgi?id=1231167

**Comment by bparees** [comment]
Note that this is only needed for when you "docker run" manually, not an openshift doc issue.

**Comment by bparees** [comment]
@mnagy bump.  this would be an easy issue to get closed :)

**Comment by phracek** [comment]
Closing it, feel free to re-open it.
